---
before:
  hooks:
    - go mod download

builds:
  - id: nvidia_gpu_exporter
    main: ./cmd/nvidia_gpu_exporter
    binary: nvidia_gpu_exporter
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.Version={{.Version}}
      - -X github.com/prometheus/common/version.Revision={{.Commit}}
      - -X github.com/prometheus/common/version.Branch={{.Branch}}
      - -X github.com/prometheus/common/version.BuildUser=goreleaser
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
     - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386

archives:
  - id: nvidia_gpu_exporter-archive
    builds:
      - nvidia_gpu_exporter
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files: 
      - LICENSE

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^build(\(.+\))?:'
      - '^chore(\(.+\))?:'
      - '^cd(\(.+\))?:'
      - '^ci(\(.+\))?:'
      - '^cicd(\(.+\))?:'
      - '^docker(\(.+\))?:'
      - '^docs(\(.+\))?:'
      - '^refactor(\(.+\))?:'
      - '^test(\(.+\))?:'
      - Merge pull request
      - Merge branch
      - go mod tidy

dockers:
  - image_templates:
      - docker.io/utkuozdemir/nvidia_gpu_exporter:{{ .Version }}-amd64
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
  - image_templates:
      - docker.io/utkuozdemir/nvidia_gpu_exporter:{{ .Version }}-arm64
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/arm64
  - image_templates:
      - docker.io/utkuozdemir/nvidia_gpu_exporter:{{ .Version }}-armv7
    use: buildx
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/arm/v7

docker_manifests:
  - name_template: docker.io/utkuozdemir/nvidia_gpu_exporter:{{ .Version }}
    image_templates:
      - docker.io/utkuozdemir/nvidia_gpu_exporter:{{ .Version }}-amd64
      - docker.io/utkuozdemir/nvidia_gpu_exporter:{{ .Version }}-arm64
      - docker.io/utkuozdemir/nvidia_gpu_exporter:{{ .Version }}-armv7

# To test docker image push, uncomment the following and run
# goreleaser release --skip-validate --rm-dist --debug
#release:
#  disable: true

scoop:
  bucket:
    owner: utkuozdemir
    name: scoop_nvidia_gpu_exporter
    token: "{{ .Env.PRIVATE_ACCESS_TOKEN }}"
  commit_author:
    name: Utku Ozdemir
    email: uoz@protonmail.com
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: https://github.com/utkuozdemir/nvidia_gpu_exporter
  description: Nvidia GPU exporter for prometheus using nvidia-smi binary
  license: MIT

aurs:
  name: nvidia-gpu-exporter-bin
  homepage: https://github.com/utkuozdemir/nvidia_gpu_exporter
  description: Nvidia GPU exporter for prometheus using nvidia-smi binary
  maintainers:
    - kpj <kim.philipp.jablonski@gmail.com>
  license: MIT
  private_key: '{{ .Env.AUR_KEY }}'
  git_url: 'ssh://aur@aur.archlinux.org/nvidia-gpu-exporter-bin.git'
  package: |-
    # systemd
    install -Dm644 "systemd/nvidia_gpu_exporter.service" "$pkgdir/usr/lib/systemd/system/nvidia-gpu-exporter.service"
    echo 'u nvidia_gpu_exporter - "Prometheus Nvidia GPU exporter user"' > "$pkgdir/usr/lib/sysusers.d/nvidia-gpu-exporter.conf"

    # binary
    install -Dm755 "$srcdir/nvidia_gpu_exporter" "$pkgdir/usr/bin/nvidia-gpu-exporter"

    # license
    install -Dm644 "$srcdir/LICENSE" "$pkgdir/usr/share/licenses/nvidia-gpu-exporter/LICENSE"
  url_template: " https://github.com/utkuozdemir/nvidia_gpu_exporter/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
